import { emptyDoc, makeTask, makeDep } from "./factory";
import type { Discipline, Status } from "./types";
/** Illustrative EPC project. Only used for a new, empty browser; existing documents are retained. */
export function showcaseDoc() {
  const doc = emptyDoc("千葉プラント 増設プロジェクト");
  doc.project.description =
    "サンプルデータ — 架空のEPCプロジェクト。自由に編集してお試しください。";
  doc.project.dataDate = "2026-09-01";
  const rows: [
    string,
    string,
    Discipline,
    number,
    Status,
    number,
    string,
    number,
    number,
    boolean?,
  ][] = [
    ["プロジェクト開始", "1.1", "E", 0, "DONE", 100, "設計1課", 40, 60, true],
    ["設計条件の確認", "1.1", "E", 4, "DONE", 100, "設計1課", 340, 60],
    ["基本設計", "1.1", "E", 10, "DONE", 100, "設計1課", 640, 60],
    ["主要機器の仕様確定", "1.2", "E", 8, "IN_PROGRESS", 70, "機械課", 940, 60],
    ["配置・配管設計", "1.2", "E", 12, "IN_PROGRESS", 45, "配管課", 940, 280],
    [
      "電気・計装設計",
      "1.3",
      "E",
      10,
      "IN_PROGRESS",
      30,
      "電気計装課",
      940,
      500,
    ],
    [
      "設計レビュー完了",
      "1.3",
      "E",
      0,
      "NOT_STARTED",
      0,
      "設計1課",
      1240,
      280,
      true,
    ],
    ["機器発注", "2.1", "P", 5, "ON_HOLD", 0, "調達課", 1240, 60],
    ["機器製作・検査", "2.1", "P", 20, "NOT_STARTED", 0, "調達課", 1540, 60],
    ["配管資材の調達", "2.2", "P", 14, "IN_PROGRESS", 25, "調達課", 1240, 500],
    [
      "電気機器の調達",
      "2.3",
      "P",
      16,
      "NOT_STARTED",
      0,
      "電気計装課",
      1240,
      720,
    ],
    [
      "主要機器の現地搬入",
      "2.1",
      "P",
      0,
      "NOT_STARTED",
      0,
      "調達課",
      1840,
      60,
      true,
    ],
    ["仮設・準備工事", "3.1", "C", 6, "DONE", 100, "施工管理課", 640, 720],
    ["基礎工事", "3.1", "C", 12, "IN_PROGRESS", 60, "土木1課", 940, 720],
    ["機器据付", "3.2", "C", 8, "NOT_STARTED", 0, "施工管理課", 2140, 60],
    ["配管工事", "3.2", "C", 14, "NOT_STARTED", 0, "配管課", 2440, 280],
    [
      "電気・計装工事",
      "3.3",
      "C",
      10,
      "NOT_STARTED",
      0,
      "電気計装課",
      2440,
      500,
    ],
    [
      "機械的完成",
      "3.3",
      "C",
      0,
      "NOT_STARTED",
      0,
      "施工管理課",
      2740,
      280,
      true,
    ],
    [
      "試運転・性能確認",
      "4.1",
      "C",
      7,
      "NOT_STARTED",
      0,
      "試運転課",
      3040,
      280,
    ],
    [
      "完成図書の引き渡し",
      "4.1",
      "E",
      5,
      "NOT_STARTED",
      0,
      "設計2課",
      3040,
      500,
    ],
    [
      "引き渡し完了",
      "4.2",
      "C",
      0,
      "NOT_STARTED",
      0,
      "施工管理課",
      3340,
      280,
      true,
    ],
  ];
  doc.tasks = rows.map(
    ([
      name,
      wbsCode,
      discipline,
      durationDays,
      status,
      progress,
      assignee,
      x,
      y,
      isMilestone,
    ]) =>
      makeTask(
        {
          name,
          wbsCode,
          discipline,
          durationDays,
          status,
          progress,
          assignee,
          position: { x, y },
          isMilestone,
          notes:
            name === "機器発注"
              ? "ベンダーの最終見積を確認中。機械課と仕様の差分を確認してから発注を再開する。"
              : "",
        },
        "サンプル",
      ),
  );
  const links = [
    [0, 1],
    [1, 2],
    [2, 3],
    [2, 4],
    [2, 5],
    [3, 6],
    [4, 6],
    [5, 6],
    [3, 7],
    [7, 8],
    [8, 11],
    [4, 9],
    [5, 10],
    [0, 12],
    [12, 13],
    [13, 14],
    [11, 14],
    [6, 14],
    [14, 15],
    [9, 15],
    [14, 16],
    [10, 16],
    [15, 17],
    [16, 17],
    [17, 18],
    [17, 19],
    [18, 20],
    [19, 20],
  ];
  doc.dependencies = links.map(([a, b]) =>
    makeDep(doc.tasks[a].id, doc.tasks[b].id),
  );
  doc.viewState = { collapsedWbs: ["1", "2", "3", "4"], expandLevel: 1 };
  return doc;
}
